services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cv-builder

  discovery-server:
    build:
      context: ./discovery-server

  config-server:
    build:
      context: ./config-server
    depends_on:
      - discovery-server

  auth-service:
    build:
      context: ./auth
    depends_on:
      - discovery-server
      - config-server

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
