services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cv-builder

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"

  config-server:
    build:
      context: ./config-server
    depends_on:
      - discovery-server
    ports:
      - "8888:8888"

  auth-service:
    build:
      context: ./auth
    depends_on:
      - discovery-server
      - config-server
    ports:
      - "8080:8080"

  api-service:
    build:
      context: ./api
    depends_on:
      - discovery-server
      - config-server
    ports:
      - "8090:8090"

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
