services:
  postgres:
    container_name: cv-db
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cv-builder

  discovery-server:
    container_name: cv-discovery
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"

  config-server:
    container_name: cv-config
    build:
      context: ./config-server
    depends_on:
      - discovery-server
    ports:
      - "8888:8888"

  auth-service:
    container_name: cv-auth
    build:
      context: ./auth
    depends_on:
      - discovery-server
      - config-server
    ports:
      - "8080:8080"

  api-service:
    container_name: cv-api
    build:
      context: ./api
    depends_on:
      - discovery-server
      - config-server
    ports:
      - "8090:8090"

  ai-service:
    container_name: cv-ai
    build:
      context: ./ai
    depends_on:
      - discovery-server
      - config-server
    ports:
      - "8091:8091"

  web:
    container_name: cv-web
    build:
      context: ./web
    depends_on:
      - discovery-server
      - config-server
      - auth-service
      - api-service
      - ai-service
    ports:
      - "5173:5173"

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
