services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
