concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "first"
  url = "https://gitlab.com"
  id = 48162998
  token = "glrt-XhGrvGsKirKdWLgTTZRPbW86MQpwOjE2b3FzOQp0OjMKdTo3MjJ4NRg.01.1j09yae50"
  token_obtained_at = 2025-07-17T19:05:47Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "cv-builder-spring-discovery-server"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
