jwt:
  public:
    key: ${auth.jwt.public-key}
spring:
  application:
    name: api-service
  datasource:
    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/cv-builder}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cv-builder}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        enabled: true
        max-attempts: 20 # Tente 20 vezes
        initial-interval: 2000 # Comece esperando 2 segundos
        max-interval: 10000 # Espera máxima entre tentativas
        multiplier: 1.5 # Aumenta a cada tentativa

  config:
    # import: "configserver:http://localhost:8888"
    import: "configserver:http://config-server:8888"

eureka:
  client:
    service-url:
      # defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      defaultZone: ${EUREKA_SERVER:http://discovery-server:8761/eureka}

server:
  port: 8090
