jwt:
  public:
    key: classpath:app.pub
spring:
  application:
    name: ai-service

  profiles:
    active: dev

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        enabled: true
        max-attempts: 20 # Tente 20 vezes
        initial-interval: 2000 # Comece esperando 2 segundos
        max-interval: 10000 # Espera máxima entre tentativas
        multiplier: 1.5 # Aumenta a cada tentativa

  config:
    # import: "configserver:http://localhost:8888"
    import: "configserver:http://config-server:8888"

eureka:
  client:
    service-url:
      # defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      defaultZone: ${EUREKA_SERVER:http://discovery-server:8761/eureka}

gemini:
  api:
    key: xxxxx
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

server:
  port: 8091
