spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5433/cv-builder
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cloud:
    config:
      uri: "${SPRING_CONFIG_SERVER:http://localhost:8888}"
  config:
    import: "${SPRING_CONFIG_SERVER:configserver:http://localhost:8888}"
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_SERVER:http://localhost:8761/eureka/}
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
