server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "${SPRING_CONFIG_URL:https://github.com/do-you-have-brio/cv-builder-config}"

eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_SERVER:http://localhost:8761/eureka}
