server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/do-you-have-brio/cv-builder-config"

eureka:
  client:
    service-url:
      # defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      defaultZone: ${EUREKA_SERVER:http://discovery-server:8761/eureka}
